export type ChecklistItem = { id: string; name: string; category: string; checked: boolean };
export type ChecklistCategory = { id: string; name: string; color: string };
export type BudgetItem = { id: string; name?: string; detail?: string; category: string; amount: number; currency?: string; paymentMethod?: string };
export type Reservation = { id: string; title: string; type: string; date: string; endDate?: string; time?: string; location?: string; departureLocation?: string; arrivalLocation?: string; departureTime?: string; arrivalTime?: string; airline?: string; terminal?: string; reservationNumber?: string; cost: number; memo: string; link?: string };
export type ReservationDocument = { id: string; reservationId: string; fileName: string; storagePath: string; mimeType: string; size: number; createdAt: string };
export type Place = { id: string; name: string; type: string; address: string; latitude?: number; longitude?: number; expectedCost: number; visitDate?: string; mustGo: boolean; visited: boolean; memo: string };
export type ScheduleItem = { id: string; date: string; title: string; time: string; endTime?: string; durationMinutes?: number; type: string; placeId?: string; note: string; completed: boolean };
export type Expense = { id: string; name?: string; amount: number; currency: string; category: string; placeId?: string; payerId?: string; memo: string; date: string; time: string; krwAmount?: number };
export type Traveler = { id: string; name: string };
export type Souvenir = { id: string; name: string; estimatedPrice: number; purchased: boolean; actualPrice: number; memo: string };
export type ExchangePlan = { from: string; to: string; rate: number; expectedCash: number; cardEstimate: number; plannedExchange: number; actualExchange: number };
export type WeatherDay = { date: string; temperature: number; condition: string; icon: string };
export type DashboardItem = { id: string; kind: "do" | "eat" | "souvenir" | "tip"; title: string; detail?: string; url?: string; category?: string };
export type TripState = {
  packing: ChecklistItem[];
  packingCategories: ChecklistCategory[];
  preparation: ChecklistItem[];
  budget: BudgetItem[];
  budgetCategories: string[];
  budgetCategoryColors: Record<string, string>;
  paymentMethods: string[];
  paymentMethodColors: Record<string, string>;
  expenseCategories: string[];
  reservationCategories: string[];
  reservationCategoryColors: Record<string, string>;
  reservations: Reservation[];
  places: Place[];
  schedule: ScheduleItem[];
  expenses: Expense[];
  travelers: Traveler[];
  souvenirs: Souvenir[];
  exchange: ExchangePlan;
  weather: WeatherDay[];
  review: { rating: number; comment: string; goodThings: string; badThings: string; revisitPlaces: string };
  dashboardItems: DashboardItem[];
};
