"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { totalsByCurrency } from "@/lib/money";
import { useLanguage } from "@/lib/i18n";
import { useTripData } from "@/lib/trip-context";

const defaultRates: Record<string, number> = { KRW: 1, JPY: 9.2, USD: 1350, EUR: 1500, GBP: 1750, CNY: 190, TWD: 42, THB: 39, VND: 0.054, SGD: 1050, AUD: 880, CAD: 980, HKD: 175, PHP: 24 };

export default function ActualBudgetPage() {
  const { tripId } = useParams<{ tripId: string }>(); const { language } = useLanguage(); const ko = language === "ko"; const { state } = useTripData(); const [rates, setRates] = useState(defaultRates);
  useEffect(() => { fetch("/api/exchange-rates").then((response) => response.ok ? response.json() : null).then((data: { rates?: Record<string, number> } | null) => { if (data?.rates) setRates((current) => ({ ...current, ...data.rates })); }).catch(() => undefined); }, []);
  const totals = totalsByCurrency(state.expenses); const totalKrw = useMemo(() => state.expenses.reduce((sum, item) => sum + item.amount * (rates[item.currency] || 0), 0), [rates, state.expenses]);
  return <main className="min-h-screen px-5 py-8 pb-16 sm:px-10 lg:px-20 lg:py-12"><div className="mx-auto max-w-4xl"><Link href={`/trips/${tripId}/before/budget`} className="text-sm font-bold text-[var(--color-primary)]">← {ko ? "예산 계획" : "Budget plan"}</Link><p className="eyebrow mt-10 mb-3">{ko ? "실제 사용" : "Actual spending"}</p><h1 className="text-4xl font-bold">{ko ? "실제로 사용한 비용" : "What you actually spent"}</h1><p className="mt-2 muted">{ko ? "여행 중 기록한 지출을 예산과 구분해 확인하세요." : "Review recorded expenses separately from your plan."}</p><section className="mt-9 grid gap-5 md:grid-cols-3"><div className="card bg-[var(--color-primary)] p-6 text-white md:col-span-2"><p className="text-sm font-semibold text-white/70">{ko ? "실제 사용액 (원화 환산)" : "Actual spent in KRW"}</p><p className="mt-3 text-4xl font-bold">₩{Math.round(totalKrw).toLocaleString("ko-KR")}</p><p className="mt-3 text-xs text-white/70">{state.expenses.length}{ko ? "건의 지출" : " expenses"}</p></div><div className="card p-6"><p className="eyebrow mb-2">{ko ? "통화별 실제 사용액" : "Actual by currency"}</p><div className="space-y-2">{Object.entries(totals).length ? Object.entries(totals).map(([currency, amount]) => <p className="flex justify-between text-sm" key={currency}><span className="muted">{currency}</span><strong>{amount.toLocaleString()}</strong></p>) : <p className="text-sm muted">{ko ? "기록된 지출이 없습니다." : "No expenses recorded."}</p>}</div></div></section><section className="card mt-5 p-6"><div className="flex items-center justify-between"><div><p className="eyebrow mb-2">{ko ? "지출 목록" : "Expense list"}</p><h2 className="text-xl font-bold">{ko ? "사용 내역" : "Spending history"}</h2></div><Link href={`/trips/${tripId}/during`} className="text-sm font-bold text-[var(--color-primary)]">{ko ? "지출 추가 →" : "Add expense →"}</Link></div><div className="mt-5 space-y-3">{state.expenses.length ? state.expenses.map((entry) => <article className="rounded-2xl bg-[var(--color-background)] p-4" key={entry.id}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{entry.memo || entry.category}</p><p className="mt-1 text-xs muted">{entry.date} · {entry.category}{entry.placeId ? " · 장소 연결" : ""}</p></div><strong>{entry.currency} {entry.amount.toLocaleString()}</strong></div></article>) : <p className="py-8 text-center text-sm muted">{ko ? "아직 실제 사용 내역이 없습니다." : "No actual spending recorded yet."}</p>}</div></section></div></main>;
}
