"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { formatTotals } from "@/lib/money";
import { useTripStore } from "@/lib/trip-store";

type TripMeta = { title: string; dates: string; status: string };

export default function TripPage() {
  const { tripId } = useParams<{ tripId: string }>();
  const { state } = useTripStore(tripId);
  const [trip, setTrip] = useState<TripMeta>({ title: tripId === "tokyo" ? "Tokyo, Japan" : "Your new journey", dates: tripId === "tokyo" ? "Sep 10 — Sep 15, 2026 · 5 nights" : "Dates to be planned", status: "planning" });
  const [savingStatus, setSavingStatus] = useState(false);
  useEffect(() => { const load = async () => { try { const local = JSON.parse(window.localStorage.getItem("voyage:trips") || "[]").find((item: { id: string }) => item.id === tripId); if (local) setTrip({ title: local.title || `${local.city}, ${local.country}`, dates: `${local.startDate} — ${local.endDate}`, status: String(local.status || "planning").toLowerCase() }); const response = await fetch(`/api/trips/${tripId}`); if (response.ok) { const result = await response.json(); if (result.trip) setTrip({ title: String(result.trip.title), dates: `${String(result.trip.start_date ?? "Dates to be planned")} — ${String(result.trip.end_date ?? "")}`, status: String(result.trip.status ?? "planning") }); } } catch { /* fallback title */ } }; void load(); }, [tripId]);
  const completeTrip = async () => { setSavingStatus(true); setTrip((current) => ({ ...current, status: "completed" })); try { const trips = JSON.parse(window.localStorage.getItem("voyage:trips") || "[]"); window.localStorage.setItem("voyage:trips", JSON.stringify(trips.map((item: { id: string }) => item.id === tripId ? { ...item, status: "Completed" } : item))); await fetch(`/api/trips/${tripId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "completed" }) }); } finally { setSavingStatus(false); } };
  const packed = state.packing.length ? Math.round(state.packing.filter((item) => item.checked).length / state.packing.length * 100) : 0;
  const total = formatTotals(state.expenses);
  const sections = [{ key: "before", label: "Before", title: "Get ready", text: `${packed}% packing complete`, emoji: "◌" }, { key: "during", label: "During", title: "Make memories", text: `${state.schedule.length} plans · ${state.places.length} places`, emoji: "✦" }, { key: "after", label: "After", title: "Keep the story", text: `${total || "No spend yet"}`, emoji: "♡" }];
  return <main className="min-h-screen px-5 py-8 sm:px-10 lg:px-20 lg:py-12"><div className="mx-auto max-w-6xl"><Link href="/trips" className="text-sm font-bold text-[var(--color-primary)]">← My trips</Link><div className="mt-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow mb-3">{trip.status === "completed" ? "Travel archive" : "Your next adventure"}</p><h1 className="text-4xl font-bold">{trip.title}</h1><p className="mt-2 muted">{trip.dates}</p></div>{trip.status !== "completed" && <button onClick={completeTrip} disabled={savingStatus} className="rounded-xl bg-[var(--color-primary)] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{savingStatus ? "Saving…" : "Mark trip completed"}</button>}</div><div className="mt-10 grid gap-5 md:grid-cols-3">{sections.map((item) => <Link key={item.key} href={`/trips/${tripId}/${item.key}`} className="card p-7 hover:-translate-y-1"><span className="grid size-12 place-items-center rounded-2xl bg-[var(--color-surface-muted)] text-xl text-[var(--color-primary)]">{item.emoji}</span><p className="eyebrow mt-8">{item.label}</p><h2 className="mt-2 text-2xl font-bold">{item.title}</h2><p className="mt-2 text-sm muted">{item.text}</p><span className="mt-8 block text-sm font-bold text-[var(--color-primary)]">Open section →</span></Link>)}</div><div className="card mt-7 p-7"><div className="flex items-center justify-between"><div><p className="eyebrow mb-3">Trip snapshot</p><h2 className="text-2xl font-bold">A little more ready every day.</h2></div><span className="text-sm font-bold text-[var(--color-primary)]">{packed}% ready</span></div><div className="mt-6 grid grid-cols-3 gap-3">{[[String(state.places.length), "Places"], [total || "—", "Spent"], [String(state.places.filter((place) => place.mustGo).length), "Must go"]].map(([value, label]) => <div key={label} className="rounded-2xl bg-[var(--color-background)] p-4"><p className="text-xl font-bold">{value}</p><p className="mt-1 text-xs muted">{label}</p></div>)}</div></div></div></main>;
}
